export {default as Blog} from './blog'
export {default as Features} from './features'
export {default as Header} from './header'
export {default as WhatsGpt} from './whatsGPT'
export {default as Footer} from './footer'